title: StreamerLyfe
description: Get started with streaming using our resources.

baseurl:
url:
dev_environment: false

google_analytics:
  account: UA-105271832-1
typekit: true
twitter_username: StreamerLyfe

extlinks:
  attributes: {rel: nofollow, target: _blank}
  rel_exclude: {'steamerlyfe.com'}

exclude: ['README.md', 'CNAME', 'Gruntfile.js', 'package.json', 'node_modules', 'css', '_scss']
keep_files: ['_site/css']
markdown: kramdown
permalink: /:categories/:title/
