title: StreamerLyfe
description: A gold mine of resources, experiences, wisdom, and tips for the streamer.

baseurl:
url: http://www.streamerlyfe.com
dev_environment: true

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
keep_files: ['_site/css']
markdown: kramdown
permalink: /:categories/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-livereload
  - jekyll-extlinks

livereload: true

extlinks:
  attributes: {rel: nofollow, target: _blank}
  rel_exclude: {'steamerlyfe.com'}

google_analytics:
  account: UA-105271832-1
typekit: true
twitter_username: StreamerLyfe