title: StreamerLyfe
description: Get started with streaming using our resources.

baseurl:
url:
dev_environment: true

google_analytics:
  account: UA-105271832-1

exclude: ['README.md', 'CNAME', 'Gruntfile.js', 'package.json', 'node_modules', 'css', '_scss']
keep_files: ['_site/css']
markdown: kramdown
