title: StreamerLyfe
description: Get started with streaming using our resources.

baseurl: /
url:

google_analytics:
  account:

exclude: ['README.md', 'CNAME', 'Gruntfile.js', 'package.json', 'node_modules', 'css', '_scss']
keep_files: ['_site/css']
