title: StreamerLyfe
description: A gold mine of resources, experiences, wisdom, and tips for the streamer.

baseurl:
url: http://www.streamerlyfe.com
dev_environment: true

google_analytics:
  account: UA-105271832-1
typekit: true
twitter_username: StreamerLyfe

extlinks:
  attributes: {rel: nofollow, target: _blank}
  rel_exclude: {'steamerlyfe.com'}

exclude: ['README.md', 'Gruntfile.js', 'package.json', 'package-lock.json', 'node_modules', 'css', '_scss']
keep_files: ['_site/css']
markdown: kramdown
permalink: /:categories/:title/
